### PR TITLE
fix request bug - fix bug for some days - replace khayam by jdatetime

### PR DESCRIPTION
**Pull request by samanjalinous**
- fix the request bug that returns just a month from time.ir
- fix the bug for duplicate holiday dates (ex: 13th Farvardin)
- use jdatetime as date convertor which is more updated

### CODE REVIEW

**Comment by hadi-gharibi** [comment]
@samanjalinous Thanks for your contribution.  A couple of points for merging your requests:

- [x]  Set the name to `jalali_date` instead of `jdate_time` for version compatibility
- [x]  Provide an example of the bug you mentioned(What time range would make the duplication problem)
- [x]  Explain a bit more about `fix the request bug that returns just a month from time.ir`

Cheers

**Comment by samanjalinous** [comment]
@hadi-gharibi Thanks for your response.
jalai_date has set for version comaptibility.

request bug can be seen in execution of sample example with configuration:
python irholiday2csv --strat_year 1395 --end_year 1400
it returns a csv file contains events related to CURRENT solar calendar(1401) from Farvardin to Esfand for each year.
this problem solved by modification of request structure(url+'?'+POSTstr), with this new format there is no need to send request header as well.

duplicate holiday dates is not suitable statement for second problem sorry for that. the issue can be explained more clearly as follows.
for some of years (e.g. 1399) holiday state incorrectly reported(0 rather than 1) in holiday column, for some of days( e.g. 13 Farvardin, 29 Esfand).
this is due to left merging of a1 and a2 dataframes represented for events and holidays respectively. this problem was solved by outer merging and some modifications
imposed on "holiday_correction" function.

**Comment by hadi-gharibi** [comment]
@samanjalinous Thanks for your detailed explanation. I will review it and hopefully will be merged by the end of next week. Thanks for your contribution and happy coding :)

**Comment by samanjalinous** [comment]
@hadi-gharibi Thank you very much :). It's my honor :)

**Pull request merged**
